-- MySQL Script generated by MySQL Workbench
-- Tue May  5 15:25:40 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pt_app_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pt_app_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pt_app_db` DEFAULT CHARACTER SET utf8 ;
USE `pt_app_db` ;

-- -----------------------------------------------------
-- Table `pt_app_db`.`Trainers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pt_app_db`.`Trainers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `version` VARCHAR(45) NOT NULL,
  `createdAt` DATE NOT NULL,
  `updatedAt` DATE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pt_app_db`.`Clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pt_app_db`.`Clients` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `birthday` DATE NULL,
  `weight` INT NULL,
  `height` INT NULL,
  `objective` LONGTEXT NULL,
  `version` VARCHAR(45) NOT NULL,
  `createdAt` DATE NOT NULL,
  `updatedAt` DATE NOT NULL,
  `createdBy` VARCHAR(45) NULL,
  `updatedBy` VARCHAR(45) NULL,
  `Trainers_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Trainers_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_Clients_Trainers_idx` (`Trainers_id` ASC) VISIBLE,
  CONSTRAINT `fk_Clients_Trainers`
    FOREIGN KEY (`Trainers_id`)
    REFERENCES `pt_app_db`.`Trainers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pt_app_db`.`Plans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pt_app_db`.`Plans` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `version` VARCHAR(45) NOT NULL,
  `createdAt` DATE NOT NULL,
  `updatedAt` DATE NOT NULL,
  `Trainers_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Trainers_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Plans_Trainers1_idx` (`Trainers_id` ASC) VISIBLE,
  CONSTRAINT `fk_Plans_Trainers1`
    FOREIGN KEY (`Trainers_id`)
    REFERENCES `pt_app_db`.`Trainers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pt_app_db`.`Exercises`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pt_app_db`.`Exercises` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `version` VARCHAR(45) NOT NULL,
  `createdAt` DATE NOT NULL,
  `updatedAt` DATE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pt_app_db`.`Files`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pt_app_db`.`Files` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `path` VARCHAR(45) NOT NULL,
  `version` VARCHAR(45) NOT NULL,
  `createdAt` DATE NOT NULL,
  `Exercises_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Exercises_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Files_Exercises1_idx` (`Exercises_id` ASC) VISIBLE,
  CONSTRAINT `fk_Files_Exercises1`
    FOREIGN KEY (`Exercises_id`)
    REFERENCES `pt_app_db`.`Exercises` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pt_app_db`.`Feedback`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pt_app_db`.`Feedback` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `text` LONGTEXT NOT NULL,
  `createdAt` DATETIME NULL,
  `Clients_id` INT UNSIGNED NOT NULL,
  `Clients_Trainers_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Clients_id`, `Clients_Trainers_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Messages_Clients1_idx` (`Clients_id` ASC, `Clients_Trainers_id` ASC) VISIBLE,
  CONSTRAINT `fk_Messages_Clients1`
    FOREIGN KEY (`Clients_id` , `Clients_Trainers_id`)
    REFERENCES `pt_app_db`.`Clients` (`id` , `Trainers_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pt_app_db`.`Configurations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pt_app_db`.`Configurations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `key` VARCHAR(45) NOT NULL,
  `value` VARCHAR(45) NOT NULL,
  `version` VARCHAR(45) NOT NULL,
  `createdAt` DATE NOT NULL,
  `updatedAt` DATE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pt_app_db`.`Plans_has_Exercises`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pt_app_db`.`Plans_has_Exercises` (
  `Plans_id` INT NOT NULL,
  `Plans_Trainers_id` INT NOT NULL,
  `Exercises_id` INT NOT NULL,
  PRIMARY KEY (`Plans_id`, `Plans_Trainers_id`, `Exercises_id`),
  INDEX `fk_Plans_has_Exercises_Exercises1_idx` (`Exercises_id` ASC) VISIBLE,
  INDEX `fk_Plans_has_Exercises_Plans1_idx` (`Plans_id` ASC, `Plans_Trainers_id` ASC) VISIBLE,
  CONSTRAINT `fk_Plans_has_Exercises_Plans1`
    FOREIGN KEY (`Plans_id` , `Plans_Trainers_id`)
    REFERENCES `pt_app_db`.`Plans` (`id` , `Trainers_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Plans_has_Exercises_Exercises1`
    FOREIGN KEY (`Exercises_id`)
    REFERENCES `pt_app_db`.`Exercises` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
